### ISSUE TITLE
Simple example of creating a CRS object from PROJ.4 string

### ISSUE THREAD

**Issue by djhoese** [karimbahgat/PyCRS#21]
I typically deal with CRS information as PROJ.4 strings or dictionaries. It would be nice to have an example in the README (or in sphinx documentation?) of how I can create a CRS object from these. Then I could add it to my own objects in place of the PROJ.4 strings/dicts and maybe do things like `isinstance(my_crs, CRS)` for any special handling. Can I do `from pycrs import CRS`?

**Comment by karimbahgat** [comment]
Good point, previous documentation was more than lacking. Now added more extensive documentation and examples of all functionality, incl how to load proj4. 

The main CRS object is now available from the toplevel, so checking for instances can be done as you suggest: `isinstance(my_crs, pycrs.CRS)`. 

For proj4 as dict vs string, see #23.

**Comment by djhoese** [comment]
Thanks for the added documentation in the README. May be nice to make a sphinx documentation website and host it on readthedocs (or pythonhosted.org as you have it now). You could then easily have the API docs and the examples in the same location. Seems like you have the build output from making the documentation but I don't see how it is created (usually I don't see the build directory in the repository).

**Comment by karimbahgat** [comment]
That's true, currently the API reference is just plain. Would be good to give that a frontpage based on the readme so it could all be together. Self-assigned new issue in #24. 

It's a bit different since I use my own home-made package upload manager [pipy](https://github.com/karimbahgat/pipy), which in turn relies on [pdoc](https://github.com/mitmproxy/pdoc) to create the html docs and save them in `build`, and automatically uploads to pythonhosted.org. 

Sticking with it for now, but in the future I may consider switching to something more contributor friendly.
