### ISSUE TITLE
Toplevel CRS wrapper class

### ISSUE THREAD

**Issue by karimbahgat** [karimbahgat/PyCRS#26]
Currently, I created the CRS class as a sort of wrapper around either GeogCRS or ProjCRS (which have different attributes/layouts), so that the user can always know what to expect. These are then accessed via the "toplevel" attribute. But the CRS class has nothing specifically of value and in a way feels like a wasteful layer to always have to go through the "toplevel" attribute. 

1. In deciding the API for the first stable version, is this wrapper a good thing, or would it be better not having the generic CRS class and instead directly receiving a GeogCRS or ProjCRS when parsing a crs format? This would mean they also had to use these directly when creating a crs from scratch. 
2. How should users check if their crs is geographic or projected, just through instance checking, or also provide a "type" attribute to indicate the type?

**Comment by djhoese** [comment]
In my opinion (and I can be very opinionated if you need me to be) you should use parent/subclassing. You have one base class `CRS` and any "specific" versions of that are subclasses. Any functionality that is shared between the types of CRS objects can be defined in the `CRS` class. Anything that has to be customized for a specific CRS type can be overridden in the subclass by redefining the method or by having the base class use a known attribute/property that can be specified by the subclass. For example:

```python
class CRS(object):
    pass

class GeogCS(CRS):
    ...

class ProjCS(CRS):
    ...

```

When I started writing this comment I thought I could have an example with the existing functionality but I see what you're saying now about the base class not really doing much. I'm also not used to splitting CRS objects up by Proj and Geog, but I also typically deal with PROJ.4 strings instead of WKT where the difference is more clear, so I'm not sure what *needs* to be separated. I think in the long run it may be best to have the base `CRS` class even though most people might say that it is premature subclassing. I just want to be able to do `isinstance(my_crs, CRS)` to know if that's what I'm dealing with. However, now that I think about it, how often would I actually need to do that. Probably not very often.

For your second question, how often do you think people need to know the difference rather than just using whatever is returned by `to_ogc_wkt` or whatever? I don't think a type attribute is needed.

One feature that was brought up on that xarray/geoxarray issue was wanting to be able to take a CRS-like object and use the `__getitem__` method to use bracket access to projection parameters like `my_crs['lon_0']` or something like that. Not sure if proj.4 parameter naming is the best thing, but yeah it was brought up and I think it could be a good idea. Not sure how to accomplish this with the current interfaces though given how everything is split up in to its own class.

I also feel like the way I would have done this is put the crs-specific parsing logic in to a crs module along side the CRS classes that get returned. If the interface is clean enough you could even do a class method `from_proj4` on the CRS class that parses a proj4 str/dict and returns the proper CRS class. That is how I would do it, doesn't mean the way it is done now is wrong or bad. Just being opinionated 😉 and laying out the options I see available.

Thanks for working so hard to make this package more usable for others.

**Comment by djhoese** [comment]
Another thought on functionality that could be added to these classes (if it doesn't exist somewhere else) would be a "sanitize" or "normalize" function so that I could take any user's PROJ.4 string and get a "consistent" PROJ.4 string back with defaults fill in.

I'm completely willing to help add any of the features or changes I bring up, but I need to slowly get caught up on how you use your own package, where you see it going, and what you think about things that I bring up.

**Comment by karimbahgat** [comment]
No worries at all about the length or strong opinions, I actually prefer that. It's great to see someone else with an interest in the project, helps keep it moving along, and find solutions for questions I'm unsure about. 

The idea of which toplevel class to use is the last API change I want to figure out before making the first stable 1.0 release. Based on your answer so far, it seems the best for now would be to make GeogCRS and ProjCRS subclasses of CRS. That way we avoid the unnecessary .toplevel attribute, can still do isinstance(my_crs, CRS), *but* if creating from scratch would have to call on the correct one, either GeogCRS or ProjCRS. Although I don't necessarily like the naming of ProjCRS and GeogCRS (they're based on the WKT 1.0 API), and unless you have any other opinions on this, I think I'll just go ahead with that for now. 

Finally, I'm happy you say you would help add features etc, and I'd be happy to make you a maintainer too if that would make it easier for you. In terms of helping you be on the same page, what type of information would be useful for you to know in terms of how I see the project, how I have organized and use it, philosophy, etc? I'd be happy to do that to help you understand the framework within which you can contribute, and then maybe add that to the docs in a section for contributors. 

About some of the other topics, I will raise and respond to these in separate issues.

**Comment by karimbahgat** [comment]
It seems like it may be problematic subclassing CRS in ProjCRS and GeogCRS after all, so now I remember why I did it this way. 

The problem is that GeogCS can either be the toplevel CRS (in which case it adds "+proj=longlat" and "+nodef"), or it can be a sub-component of ProjCS (in which case these should not be added or would be duplicate). Since the proj4 representation is different depending on whether GeogCS is toplevel or not, we need a way to check for this, and is why I instead made the separate CRS class that we know is always toplevel. 

One way to check if it's toplevel would be to check if it has a parent, but currently we have no system of tracking parents, and if we set this as an attribute it could break easily if users try to tweak or recombine instances. I think the only way to correctly check for toplevel is to continue to force the users to wrap their GeogCS or ProjCS inside the CRS class explicitly as a way to indicate that is their final CRS/toplevel. One thing we could do however, is redirect CRS attribute access to its 'toplevel' attribute, so that at least we avoid the unnessary attribute call. 

Thoughts on this @djhoese, maybe I'm overthinking things, or maybe there is some other solution to this I haven't thought of?

**Comment by karimbahgat** [comment]
Decided on dealing directly with either GeogCS or ProjCS and was able to fix the issues I raised above. The user then simply checks for which type via the `cs_type` attribute. 
That means entirely dropping the unnecessary CRS class wrapper and no longer having to go through the `toplevel` attribute.

**Comment by djhoese** [comment]
Sounds good. Thank you.
