### ISSUE TITLE
How to get EPSG code from Shapefile?

### ISSUE THREAD

**Issue by fitoprincipe** [karimbahgat/PyCRS#46]
Hello,

First of all I want to thank you Karim for this and all your "pure python" code related to GIS. I am making a python package and I don't want to have GDAL/OGR as a dependency =P

I am interested in getting the EPSG code from a know projection using a `.prj` file, is that functionality implemented? I couldn't find it. I managed to do it myself, but I wanted to know if you made an approach to it. This is my (simple) code in case anyone else is interested:

``` python
import requests
BASEURL = 'http://prj2epsg.org/search.json'
def get_epsg(wkt):
    """ Get EPSG code from WKT projection """
    params = dict(mode='wkt', terms=wkt)
    response = requests.get(BASEURL, params)
    return response.json()
```

**Comment by karimbahgat** [comment]
Glad to hear, and that I'm not the only one! :) 
This is definitely a functionality that should be added in the next release, as it has been requested several times recently. 

If you'd be able to make it as a PR, I'd happily merge it. I'd only ask to switch to use pure urllib (instead of requests), and make it a 'wkt_to_epsg()' function inside 'utils.py'. See #38 for someone else's version of the same.

**Comment by fitoprincipe** [comment]
Hi @karimbahgat :smile: 

ok! I'll try to do that. Thanks!

**Comment by fitoprincipe** [comment]
do you know another server that serves that information? we could have a "plan B" in case one server goes off or can't handle the given projection :thinking:

**Comment by fitoprincipe** [comment]
Another question @karimbahgat (sorry), `prj2epsg.org` returns a list of codes and some additional information, do you think the output should have all that information or just EPSG code? Looking at the structure of the output I was thinking in making an output like this:

```
{
  NAME: ESPG_CODE,
  ...
  exact: BOOL
}
```
For example:
```
{
  'GCS_WGS_1984': '4326',
  exact: True
}
```
I am not much into projections, so I am not really sure how this could vary.. can one `WKT` correspond to more than one `EPSG`? Looking at the site's output, it looks like yes. Then, I suppose the site makes a response when you pass a similar `WKT`, so the parameter `exact`.

**Comment by karimbahgat** [comment]
Regarding a backup site, I think prj2epsg is the only one that specifically tries to parse the wkt. One could potentially pull the search results from any of the other sites and see if any of the results are defined as an EPSG code, but from my previous testing this type of searching isn't very reliable. I have a prototype function for searching arbitrary text inside utils.py, which could potentially be used for pulling the EPSG code:
```
def crsstring_to_string(string, newformat):
    """
    Search unknown crs string for a match on spatialreference.org.
    Not very reliable, the search engine does not properly lookup all text.
    If string is correct there should only be one correct match.
    Warning: Not finished yet.
    """
    link = 'http://spatialreference.org/ref/?search=%s' %string
    searchresults = urllib2.urlopen(link).read()
    # pick the first result
    # ...regex...
    # go to its url, with extension for the newformat
    link = 'http://spatialreference.org/ref/%s/%s/%s/' %(codetype,code,newformat)
    result = urllib2.urlopen(link).read()
```
I think prj2epsg is probably sufficient though, I'm not sure how often it will go down that it will be worth it. But open to suggestions. 

It might be useful to have the entire dictionary results, since the users have to somehow determine which of the results is the correct one when there are multiple. I'd also suggest making a separate dict entry for name and epsg code, eg:

```
{
  name: 'GCS_WGS_1984',
  epsg: '4326',
  ...
  exact: True,
}
```

**Comment by fitoprincipe** [comment]
Reading your last suggestion I suppose the output is fine as it comes from the site, so #47 should be enough. What do you think?

**Comment by karimbahgat** [comment]
The output from epsg.io seems fine for now. Merged your PR, fixed Py2/3 issue, and added a convenience `to_epsg()` method for GeogCS and ProjCS. 

What's missing now is a description and demonstration of `to_epsg()` in README.md, which will then also serve as a basic docstring test. I've already tested that it works, eg something like:

```
>>> crs = pycrs.parse.from_epsg_code(4326)
>>> firstmatch = crs.to_epsg()['codes'][0]
>>> firstmatch['code']
4326
```

If you could also do some basic sanity tests, for instance `pycrs.parse.from_epsg_code(4326).to_epsg()` (Robinson projection) seems to return error results described as wkt parsing error on the "false_northing" parameter, but not sure why...

**Comment by fitoprincipe** [comment]
Sorry, I don't get the last part:

> If you could also do some basic sanity tests, for instance pycrs.parse.from_epsg_code(4326).to_epsg() (Robinson projection) seems to return error results described as wkt parsing error on the "false_northing" parameter, but not sure why...

I can't reproduce the error.. since 4326 isn't for Robinson projection :thinking: and is working fine (is the same code you used for showing it works)

**Comment by karimbahgat** [comment]
Sorry, yes the first 4326 (WGS84) was an example that works. 

The last part about the error results for Robinson was a separate example, and I accidentally just copied the code from the 4326 example. Use this code instead:

```
pycrs.parse.from_esri_code(54030).to_epsg()
```

And here's a third example that DOES work, even though it too has the False_Easting parameter:

```
pycrs.parse.from_sr_code(42).to_epsg()
```

**Comment by fitoprincipe** [comment]
Yes, I've tried it.. that is weird, and goes beyond my knowledge. Could it be an issue in `prj2epsg.org`?

**Comment by karimbahgat** [comment]
Added the method and docs for this in new v1.0.2, and just released pypi too. 
In short, the solution is to call `.to_epsg_code()` on your crs instance.
